import Image from "next/image";
import type { Metadata } from "next";
import Pikachu  from "@/assets/pikachu.webp"
//import Carrossel from "@/components/carrossel";

export const metadata: Metadata = {
  title: "PokeDéx",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    {/* <Carrossel></Carrossel> */}
    <div className="flex flex-row flex-wrap p-10 gap-5 text-lg justify-center">
      <div className=" flex flex-col  gap-5 bg-zinc-100 rounded-lg p-5 items-center justify-center  shadow-md shadow-rose-700/50 " >
        <Image src={Pikachu} alt="" className="w-full"></Image>
        <h1 className="font-bold">1: Pikachu</h1>
        <button className="p-2 bg-red-600 rounded-lg text-branco font-bold">Ver mais</button>
      </div>
    </div>
    </>
  );
}
